# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
pool:
  vmImage: windows-latest
steps:
- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $Env:DETECT_LATEST_RELEASE_VERSION = 8.4.0
      powershell "[Net.ServicePointManager]::SecurityProtocol = 'tls12'; irm https://detect.synopsys.com/detect.ps1?$(Get-Random) | iex; detect" --blackduck.url=https://https://saastest.app.blackduck.com --blackduck.trust.cert=true --detect.project.name=ADO_TEST --blackduck.api.token=Y2E4NWQ0NTMtZmVkZi00NzcyLThlZWQtM2U3YzVjMWYzZDVhOjViYTMxNmYzLWI1ZmQtNDkzMi1iNjIwLWM2YjJmOTdlMTc2Zg== --detect.detector.search.depth=6