# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger: none
pool:
  vmImage: windows-latest
steps:
- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true
- task: SynopsysDetectTask@7
  displayName: Scan project in Black Duck
  inputs:
    BlackDuckService: blackduck1
    DetectVersion: 8.0.0
    DetectArguments: |
      --blackduck.trust.cert=true
      --detect.project.name=ADO_TEST
      --blackduck.api.token=Y2E4NWQ0NTMtZmVkZi00NzcyLThlZWQtM2U3YzVjMWYzZDVhOjViYTMxNmYzLWI1ZmQtNDkzMi1iNjIwLWM2YjJmOTdlMTc2Zg==
      --detect.detector.search.depth=6